[package]
name = "i8080-emu"
version = "0.1.0"
authors = ["Jorik Cronenberg <jcronenberg@suse.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
